apiVersion: v1
kind: Namespace
metadata:
  name: spaceship
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent
  namespace: spaceship
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: agent
    namespace: spaceship
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  namespace: spaceship
  labels:
    app: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      serviceAccountName: agent
      containers:
        - name: agent
          command: ['agent']
          image: registry.onspaceship.com/spaceship/agent:master
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SPACESHIP_AGENT_ID
              value: abc123
          resources:
            limits:
              memory: 32Mi
              cpu: 100m
